# Generated by Django 5.1.1 on 2024-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messenger',
            field=models.URLField(blank=True, null=True, verbose_name='Messenger'),
        ),
        migrations.AddField(
            model_name='user',
            name='reddit',
            field=models.URLField(blank=True, null=True, verbose_name='Reddit'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
