# Generated by Django 5.1.1 on 2024-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_messenger_user_reddit_user_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('editor', 'Editor'), ('director', 'Director'), ('scriptwriter', 'Scriptwriter'), ('producer', 'Producer')], max_length=50, null=True, verbose_name='Профессия'),
        ),
    ]
