# Generated by Django 5.1.1 on 2024-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('editor', 'Editor'), ('director', 'Director'), ('scriptwriter', 'Scriptwriter'), ('producer', 'Producer')], default='', max_length=50, null=True, verbose_name='Профессия'),
        ),
    ]
