# Generated by Django 5.1.6 on 2025-02-22 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'contact-us'), (2, 'new-product')], default=1, verbose_name='Тип уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление админу',
                'verbose_name_plural': 'Уведомления админу',
            },
        ),
    ]
