# Generated by Django 5.1.6 on 2025-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_adminnotificationlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_without_email',
            field=models.BooleanField(default=False, verbose_name='Пользователь не имеет email'),
        ),
    ]
