# Generated by Django 5.1.7 on 2025-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_user_without_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_user_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ID Facebook'),
        ),
    ]
