# Generated by Django 5.1.1 on 2024-09-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
