# Generated by Django 5.1.6 on 2025-02-12 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=1024, verbose_name='Короткое описание')),
                ('cover', models.ImageField(upload_to='tutorials', verbose_name='Обложка')),
                ('pdf', models.FileField(upload_to='tutorials/pdf', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('tutorialblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tutorials.tutorialblock')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='tutorials/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
            bases=('tutorials.tutorialblock',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('tutorialblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tutorials.tutorialblock')),
                ('text', models.TextField(blank=True, default=None, max_length=10024, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
            },
            bases=('tutorials.tutorialblock',),
        ),
        migrations.AddField(
            model_name='tutorialblock',
            name='tutorial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tutorials.tutorial', verbose_name='Tutorial'),
        ),
    ]
