# Generated by Django 5.1.6 on 2025-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/pdf', verbose_name='PDF'),
        ),
    ]
