# Generated by Django 5.1 on 2024-08-28 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_type', models.CharField(choices=[('raw', 'Raw'), ('jpeg', 'Jpeg'), ('tiff', 'Tiff'), ('other', 'Other')], max_length=10, verbose_name='Тип формата')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('focal_length', models.CharField(max_length=50, verbose_name='Фокусное расстояние')),
                ('lens_type', models.CharField(max_length=20, verbose_name='Тип объектива')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('subscription', 'Subscription')], max_length=20, verbose_name='Тип доступа')),
                ('category', models.CharField(choices=[('distortion_grids', 'Distortion grids'), ('presets', 'Presets'), ('st_map', 'St map'), ('full_archives', 'Full archives')], max_length=30, verbose_name='Категория')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.camera', verbose_name='Камера')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.file', verbose_name='Файл')),
                ('file_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.format', verbose_name='Формат файла')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.lens', verbose_name='Объектив')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
