# Generated by Django 5.1 on 2024-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат файла', 'verbose_name_plural': 'Формат файлов'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name': 'Объектив', 'verbose_name_plural': 'Объективы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=255, verbose_name='Идентификатор Файла'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format_type',
            field=models.CharField(max_length=10, unique=True, verbose_name='Тип формата'),
        ),
        migrations.AlterField(
            model_name='lens',
            name='lens_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('zoom', 'Zoom')], max_length=10, verbose_name='Тип объектива'),
        ),
    ]
