# Generated by Django 5.1.1 on 2024-09-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_file_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
