# Generated by Django 5.1.1 on 2024-09-18 09:59

import apps.products.models.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_file_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='lens_type',
        ),
        migrations.AddField(
            model_name='lens',
            name='model_name',
            field=models.CharField(default='', max_length=255, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен модерацией'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.products.models.files.upload_to, verbose_name='Файл'),
        ),
    ]
