# Generated by Django 5.1.2 on 2024-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_camera_brand_remove_lens_focal_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор Файла'),
        ),
    ]
