name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH with Password
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 89.58.57.91
          username: root
          password: QWMBc99N4VmjLCf
          port: 22
          script: |
            cd /home/Matchmove_machine_site/
            git pull origin main
            docker-compose down
            docker-compose up -d